version: '3'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    networks:
      # - backend
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.docker-registry.rule=Host(`docker.mitrasinovic.co.uk`)
      - traefik.http.routers.docker-registry.entrypoints=web
      - traefik.http.routers.docker-registry.tls=false
      # Sets the maximum request body to 1GB
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=1073741824
      - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=1073741824
      - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=200000000

networks:
  #  backend:
  #    driver: bridge
  traefik-proxy:
    external: true
