version: '3'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    networks:
      - backend
  webserver:
    image: nginx:1.17.9-alpine
    container_name: registry-nginx
    restart: always
    depends_on:
      - registry
    expose:
      - 80
    environment:
      VIRTUAL_HOST: docker.mitrasinovic.co.uk
      LETSENCRYPT_HOST: docker.mitrasinovic.co.uk
      LETSENCRYPT_EMAIL: smig88@gmail.com
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - backend
      - nginx-proxy

networks:
  backend:
    driver: bridge
  nginx-proxy:
    external: true

