version: '3'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    networks:
#      - backend
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.docker-registry.rule: Host(`docker.mitrasinovic.co.uk`)
      traefik.http.routers.docker-registry.entrypoints: web
#  webserver:
#    image: nginx:1.17.9-alpine
#    container_name: registry-nginx
#    restart: always
#    depends_on:
#      - registry
#    expose:
#      - 80
#    labels:
#      traefik.enable: true
#      traefik.http.routers.docker-registry-http.rule: Host(`docker.mitrasinovic.co.uk`)
#      traefik.http.routers.docker-registry-http.entrypoints: web
#      traefik.http.routers.docker-registry.rule: Host(`docker.mitrasinovic.co.uk`)
#      traefik.http.routers.docker-registry.entrypoints: websecure
#      traefik.http.routers.docker-registry.tls.certresolver: letsencrypt
#      traefik.http.routers.docker-registry-http.middlewares: https_redirect@file
#    volumes:
#      - ./nginx-conf:/etc/nginx/conf.d
#    networks:
#      - backend
#      - traefik-proxy

networks:
#  backend:
#    driver: bridge
  traefik-proxy:
    external: true
