version: '3.9'

services:
  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
    networks:
      - traefik-proxy
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - 'node.role==manager'
      replicas: 1
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.docker-registry.rule=Host(`docker.mitrasinovic.co.uk`)
        - traefik.http.routers.docker-registry.tls=true
        - traefik.http.routers.docker-registry.middlewares=https_redirect@file, limit@docker
        - traefik.http.services.docker-registry-service.loadbalancer.server.port=5000

networks:
  traefik-proxy:
    external: true
